name: goatcounter api request workflow

# on:
#   schedule:
#     - cron: "00 00 * * *"
on: push

jobs:
  goatcounter-api-request:
    name: goatcounter api request job
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          token: ${{secrets.PAT}}

      - name: set up environment
        run: |
          python3 -m pip install --upgrade pip
          pip install requests==2.31.0
          python3 tools/goatcounter.py ${{ secrets.GOATCOUNTER_API_KEY }}

      - name: "inspect new environment"
        run: ls data/generated

      - name: push
        run: |
          git config user.name 'bot'
          git config user.email 'madsbalto@gmail.com'
          git add data/generated/count.json
          git commit -m "automated count.json update [skip ci]"
          git push
