name: goatcounter api request workflow

# on:
#   schedule:
#     - cron: "00 00 * * *"
on: push

jobs:
  goatcounter-api-request:
    name: goatcounter api request job
    runs-on: ubuntu-latest
    steps:
      - name: run goatcounter py
        run: |
          python3 -m pip install --upgrade pip
          pip install requests==2.31.0
          python3 tools/goatcounter.py ${{ secrets.GOATCOUNTER_API_KEY }}
